autoInstallPeers: true

allowBuilds:
  electron: true
  electron-winstaller: true
  esbuild: true
  sharp: true
  vue-demi: true

catalog:
  '@iconify-json/fa6-brands': 1.2.5
  '@iconify-json/mdi': 1.2.3
  '@iconify/tools': 5.0.12
  '@iconify/utils': 3.1.3
  '@intlify/unplugin-vue-i18n': 11.2.5
  '@types/archiver': 8.0.0
  '@types/luaparse': 0.2.1
  '@types/luxon': 3.7.2
  '@types/node': 26.5.1
  '@types/tail': 2.2.3
  '@unocss/preset-icons': 66.6.6
  '@unocss/preset-web-fonts': 66.6.6
  '@vitejs/plugin-vue': 6.0.7
  '@vitest/ui': 4.1.11
  archiver: 8.0.0
  archiver-utils: 5.0.2
  electron: 44.3.0
  electron-builder: 26.8.1
  electron-log: 5.4.4
  electron-store: 11.0.2
  electron-updater: 6.8.3
  floating-vue: 5.2.2
  glob: 13.0.1
  got: 16.0.0
  happy-dom: 20.14.3
  luaparse: 0.2.1
  luxon: 3.7.2
  pinia: 3.0.4
  pinia-plugin-persistedstate-2: 2.0.32
  playwright: 1.61.1
  regedit: 5.1.4
  sharp: 0.35.4
  tail: 2.2.6
  tga: 1.0.7
  typescript: 6.0.3
  unocss: 66.6.6
  vite: npm:@voidzero-dev/vite-plus-core@0.3.2
  vite-plugin-electron: 1.1.2
  vite-plugin-electron-renderer: 1.0.0
  vite-plugin-resolve: 2.5.2
  vite-plugin-vue-devtools: 8.2.1
  vite-plugin-webfont-dl: 3.12.0
  vite-plus: 0.3.2
  vitest: 4.1.11
  vitest-browser-vue: 3.1.0
  vue: 3.5.42
  vue-i18n: 11.4.10
  vue-tsc: 3.3.11

overrides:
  vite@*: 'catalog:'
  vitest@*: 'catalog:'

peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: '*'
    vitest: '*'
