/// <reference types="vite-plus" />
import { rmSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import VueI18nPlugin from "@intlify/unplugin-vue-i18n/vite";
import vue from "@vitejs/plugin-vue";
import UnoCSS from "unocss/vite";
import { defineConfig } from "vite-plus";
import type { UserConfig } from "vite-plus";
import electron from "vite-plugin-electron";
import renderer from "vite-plugin-electron-renderer";
import VueDevTools from "vite-plugin-vue-devtools";
import webfontDownload from "vite-plugin-webfont-dl";

import pkg from "./package.json";

// import { browserslistToTargets } from "lightningcss";
// import browserslist from "browserslist";

// https://vitejs.dev/config/
export default defineConfig(({ command }) => {
  rmSync("dist-electron", { recursive: true, force: true });

  const isServe = command === "serve";
  const isBuild = command === "build";
  const sourcemap = isServe || !!process.env.VSCODE_DEBUG;

  const __filename = fileURLToPath(import.meta.url);
  const __dirname = path.dirname(__filename);

  return {
    root: __dirname,
    resolve: {
      alias: [
        {
          find: /~(.+)/,
          replacement: path.join(process.cwd(), "./node_modules/$1"),
        },
        {
          find: /@\//,
          replacement: `${path.join(process.cwd(), "./src")}/`,
        },
      ],
    },
    define: {
      __APP_VERSION__: JSON.stringify(pkg.version),
      __APP_LICENSE__: JSON.stringify(pkg.license),
    },
    plugins: [
      UnoCSS(),
      VueDevTools(),
      vue(),
      electron([
        {
          // Main-Process entry file of the Electron App.
          entry: "electron/main/index.ts",
          onstart(options) {
            if (process.env.VSCODE_DEBUG) {
              console.log(/* For `.vscode/.debug.script.mjs` */ "[startup] Electron App");
            } else {
              void options.startup();
            }
          },
          vite: {
            build: {
              sourcemap,
              minify: isBuild,
              outDir: "dist-electron/main",
              rollupOptions: {
                output: {
                  format: "esm",
                  entryFileNames: "[name].mjs",
                },
                external: Object.keys("dependencies" in pkg ? pkg.dependencies : {}),
              },
            },
          },
        },
        {
          entry: "electron/preload/index.ts",
          onstart(options) {
            // Notify the Renderer-Process to reload the page when the Preload-Scripts build is complete,
            // instead of restarting the entire Electron App.
            options.reload();
          },
          vite: {
            build: {
              sourcemap: sourcemap ? "inline" : undefined,
              minify: isBuild,
              outDir: "dist-electron/preload",
              rollupOptions: {
                external: Object.keys("dependencies" in pkg ? pkg.dependencies : {}),
                output: {
                  format: "esm",
                  entryFileNames: "[name].mjs",
                },
              },
            },
          },
        },
      ]),
      renderer({
        resolve: {
          archiver: { type: "cjs" },
          regedit: { type: "cjs" },
          sharp: { type: "cjs" },
          tga: { type: "cjs" },
          got: { type: "esm" },
        },
      }),
      VueI18nPlugin({
        // you need to set i18n resource including paths!
        include: path.resolve(__dirname, "./i18n/**"),
      }),
      webfontDownload(),
    ],
    // css: {
    //   transformer: "lightningcss",
    //   lightningcss: {
    //     targets: browserslistToTargets(browserslist(">= 0.25%")),
    //   },
    // },
    build: {
      sourcemap,
      target: "esnext",
      rollupOptions: {
        output: {
          assetFileNames: "assets/[name].[ext]",
        },
      },
    },
    test: {
      globals: true,
      environment: "happy-dom",
      setupFiles: [],
      include: ["src/**/*.{test,spec}.{js,ts,jsx,tsx}"],
      exclude: ["node_modules", "dist", "dist-electron", ".git", ".cache"],
      coverage: {
        provider: "v8",
        reporter: ["text", "json"],
        exclude: [
          "node_modules/",
          "dist/",
          "dist-electron/",
          "**/*.d.ts",
          "**/*.config.*",
          "**/mockData",
        ],
      },
    },
    server: process.env.VSCODE_DEBUG
      ? (() => {
          const url = new URL(pkg.debug.env.VITE_DEV_SERVER_URL);
          return {
            lint: {
              "plugins": [
                "oxc",
                "typescript",
                "unicorn",
                "react",
                "vue"
              ],
              "jsPlugins": [
                "eslint-plugin-unocss"
              ],
              "categories": {
                "correctness": "warn"
              },
              "options": {
                "typeAware": true,
                "typeCheck": true
              },
              "env": {
                "builtin": true,
                "commonjs": true
              },
              "globals": {
                "__dirname": "readonly",
                "__filename": "readonly",
                "AbortController": "readonly",
                "AbortSignal": "readonly",
                "atob": "readonly",
                "Blob": "readonly",
                "BroadcastChannel": "readonly",
                "btoa": "readonly",
                "Buffer": "readonly",
                "ByteLengthQueuingStrategy": "readonly",
                "clearImmediate": "readonly",
                "clearInterval": "readonly",
                "clearTimeout": "readonly",
                "CompressionStream": "readonly",
                "console": "readonly",
                "CountQueuingStrategy": "readonly",
                "crypto": "readonly",
                "Crypto": "readonly",
                "CryptoKey": "readonly",
                "CustomEvent": "readonly",
                "DecompressionStream": "readonly",
                "DOMException": "readonly",
                "Event": "readonly",
                "EventTarget": "readonly",
                "fetch": "readonly",
                "File": "readonly",
                "FormData": "readonly",
                "Headers": "readonly",
                "MessageChannel": "readonly",
                "MessageEvent": "readonly",
                "MessagePort": "readonly",
                "performance": "readonly",
                "PerformanceEntry": "readonly",
                "PerformanceMark": "readonly",
                "PerformanceMeasure": "readonly",
                "PerformanceObserver": "readonly",
                "PerformanceObserverEntryList": "readonly",
                "PerformanceResourceTiming": "readonly",
                "process": "readonly",
                "queueMicrotask": "readonly",
                "ReadableByteStreamController": "readonly",
                "ReadableStream": "readonly",
                "ReadableStreamBYOBReader": "readonly",
                "ReadableStreamBYOBRequest": "readonly",
                "ReadableStreamDefaultController": "readonly",
                "ReadableStreamDefaultReader": "readonly",
                "Request": "readonly",
                "Response": "readonly",
                "setImmediate": "readonly",
                "setInterval": "readonly",
                "setTimeout": "readonly",
                "structuredClone": "readonly",
                "SubtleCrypto": "readonly",
                "TextDecoder": "readonly",
                "TextDecoderStream": "readonly",
                "TextEncoder": "readonly",
                "TextEncoderStream": "readonly",
                "TransformStream": "readonly",
                "TransformStreamDefaultController": "readonly",
                "URL": "readonly",
                "URLSearchParams": "readonly",
                "WebAssembly": "readonly",
                "WritableStream": "readonly",
                "WritableStreamDefaultController": "readonly",
                "WritableStreamDefaultWriter": "readonly",
                "addEventListener": "readonly",
                "alert": "readonly",
                "AnalyserNode": "readonly",
                "Animation": "readonly",
                "AnimationEffectReadOnly": "readonly",
                "AnimationEffectTiming": "readonly",
                "AnimationEffectTimingReadOnly": "readonly",
                "AnimationEvent": "readonly",
                "AnimationPlaybackEvent": "readonly",
                "AnimationTimeline": "readonly",
                "applicationCache": "readonly",
                "ApplicationCache": "readonly",
                "ApplicationCacheErrorEvent": "readonly",
                "Attr": "readonly",
                "Audio": "readonly",
                "AudioBuffer": "readonly",
                "AudioBufferSourceNode": "readonly",
                "AudioContext": "readonly",
                "AudioDestinationNode": "readonly",
                "AudioListener": "readonly",
                "AudioNode": "readonly",
                "AudioParam": "readonly",
                "AudioProcessingEvent": "readonly",
                "AudioScheduledSourceNode": "readonly",
                "AudioWorkletGlobalScope": "readonly",
                "AudioWorkletNode": "readonly",
                "AudioWorkletProcessor": "readonly",
                "BarProp": "readonly",
                "BaseAudioContext": "readonly",
                "BatteryManager": "readonly",
                "BeforeUnloadEvent": "readonly",
                "BiquadFilterNode": "readonly",
                "BlobEvent": "readonly",
                "blur": "readonly",
                "BudgetService": "readonly",
                "Cache": "readonly",
                "caches": "readonly",
                "CacheStorage": "readonly",
                "cancelAnimationFrame": "readonly",
                "cancelIdleCallback": "readonly",
                "CanvasCaptureMediaStreamTrack": "readonly",
                "CanvasGradient": "readonly",
                "CanvasPattern": "readonly",
                "CanvasRenderingContext2D": "readonly",
                "ChannelMergerNode": "readonly",
                "ChannelSplitterNode": "readonly",
                "CharacterData": "readonly",
                "clientInformation": "readonly",
                "ClipboardEvent": "readonly",
                "ClipboardItem": "readonly",
                "close": "readonly",
                "closed": "readonly",
                "CloseEvent": "readonly",
                "Comment": "readonly",
                "CompositionEvent": "readonly",
                "confirm": "readonly",
                "ConstantSourceNode": "readonly",
                "ConvolverNode": "readonly",
                "createImageBitmap": "readonly",
                "Credential": "readonly",
                "CredentialsContainer": "readonly",
                "CSS": "readonly",
                "CSSConditionRule": "readonly",
                "CSSFontFaceRule": "readonly",
                "CSSGroupingRule": "readonly",
                "CSSImportRule": "readonly",
                "CSSKeyframeRule": "readonly",
                "CSSKeyframesRule": "readonly",
                "CSSMatrixComponent": "readonly",
                "CSSMediaRule": "readonly",
                "CSSNamespaceRule": "readonly",
                "CSSPageRule": "readonly",
                "CSSPerspective": "readonly",
                "CSSRotate": "readonly",
                "CSSRule": "readonly",
                "CSSRuleList": "readonly",
                "CSSScale": "readonly",
                "CSSSkew": "readonly",
                "CSSSkewX": "readonly",
                "CSSSkewY": "readonly",
                "CSSStyleDeclaration": "readonly",
                "CSSStyleRule": "readonly",
                "CSSStyleSheet": "readonly",
                "CSSSupportsRule": "readonly",
                "CSSTransformValue": "readonly",
                "CSSTranslate": "readonly",
                "CustomElementRegistry": "readonly",
                "customElements": "readonly",
                "DataTransfer": "readonly",
                "DataTransferItem": "readonly",
                "DataTransferItemList": "readonly",
                "defaultstatus": "readonly",
                "defaultStatus": "readonly",
                "DelayNode": "readonly",
                "DeviceMotionEvent": "readonly",
                "DeviceOrientationEvent": "readonly",
                "devicePixelRatio": "readonly",
                "dispatchEvent": "readonly",
                "document": "readonly",
                "Document": "readonly",
                "DocumentFragment": "readonly",
                "DocumentType": "readonly",
                "DOMError": "readonly",
                "DOMImplementation": "readonly",
                "DOMMatrix": "readonly",
                "DOMMatrixReadOnly": "readonly",
                "DOMParser": "readonly",
                "DOMPoint": "readonly",
                "DOMPointReadOnly": "readonly",
                "DOMQuad": "readonly",
                "DOMRect": "readonly",
                "DOMRectList": "readonly",
                "DOMRectReadOnly": "readonly",
                "DOMStringList": "readonly",
                "DOMStringMap": "readonly",
                "DOMTokenList": "readonly",
                "DragEvent": "readonly",
                "DynamicsCompressorNode": "readonly",
                "Element": "readonly",
                "ErrorEvent": "readonly",
                "event": "readonly",
                "EventSource": "readonly",
                "external": "readonly",
                "FileList": "readonly",
                "FileReader": "readonly",
                "find": "readonly",
                "focus": "readonly",
                "FocusEvent": "readonly",
                "FontFace": "readonly",
                "FontFaceSetLoadEvent": "readonly",
                "FormDataEvent": "readonly",
                "frameElement": "readonly",
                "frames": "readonly",
                "GainNode": "readonly",
                "Gamepad": "readonly",
                "GamepadButton": "readonly",
                "GamepadEvent": "readonly",
                "getComputedStyle": "readonly",
                "getSelection": "readonly",
                "HashChangeEvent": "readonly",
                "history": "readonly",
                "History": "readonly",
                "HTMLAllCollection": "readonly",
                "HTMLAnchorElement": "readonly",
                "HTMLAreaElement": "readonly",
                "HTMLAudioElement": "readonly",
                "HTMLBaseElement": "readonly",
                "HTMLBodyElement": "readonly",
                "HTMLBRElement": "readonly",
                "HTMLButtonElement": "readonly",
                "HTMLCanvasElement": "readonly",
                "HTMLCollection": "readonly",
                "HTMLContentElement": "readonly",
                "HTMLDataElement": "readonly",
                "HTMLDataListElement": "readonly",
                "HTMLDetailsElement": "readonly",
                "HTMLDialogElement": "readonly",
                "HTMLDirectoryElement": "readonly",
                "HTMLDivElement": "readonly",
                "HTMLDListElement": "readonly",
                "HTMLDocument": "readonly",
                "HTMLElement": "readonly",
                "HTMLEmbedElement": "readonly",
                "HTMLFieldSetElement": "readonly",
                "HTMLFontElement": "readonly",
                "HTMLFormControlsCollection": "readonly",
                "HTMLFormElement": "readonly",
                "HTMLFrameElement": "readonly",
                "HTMLFrameSetElement": "readonly",
                "HTMLHeadElement": "readonly",
                "HTMLHeadingElement": "readonly",
                "HTMLHRElement": "readonly",
                "HTMLHtmlElement": "readonly",
                "HTMLIFrameElement": "readonly",
                "HTMLImageElement": "readonly",
                "HTMLInputElement": "readonly",
                "HTMLLabelElement": "readonly",
                "HTMLLegendElement": "readonly",
                "HTMLLIElement": "readonly",
                "HTMLLinkElement": "readonly",
                "HTMLMapElement": "readonly",
                "HTMLMarqueeElement": "readonly",
                "HTMLMediaElement": "readonly",
                "HTMLMenuElement": "readonly",
                "HTMLMetaElement": "readonly",
                "HTMLMeterElement": "readonly",
                "HTMLModElement": "readonly",
                "HTMLObjectElement": "readonly",
                "HTMLOListElement": "readonly",
                "HTMLOptGroupElement": "readonly",
                "HTMLOptionElement": "readonly",
                "HTMLOptionsCollection": "readonly",
                "HTMLOutputElement": "readonly",
                "HTMLParagraphElement": "readonly",
                "HTMLParamElement": "readonly",
                "HTMLPictureElement": "readonly",
                "HTMLPreElement": "readonly",
                "HTMLProgressElement": "readonly",
                "HTMLQuoteElement": "readonly",
                "HTMLScriptElement": "readonly",
                "HTMLSelectElement": "readonly",
                "HTMLShadowElement": "readonly",
                "HTMLSlotElement": "readonly",
                "HTMLSourceElement": "readonly",
                "HTMLSpanElement": "readonly",
                "HTMLStyleElement": "readonly",
                "HTMLTableCaptionElement": "readonly",
                "HTMLTableCellElement": "readonly",
                "HTMLTableColElement": "readonly",
                "HTMLTableElement": "readonly",
                "HTMLTableRowElement": "readonly",
                "HTMLTableSectionElement": "readonly",
                "HTMLTemplateElement": "readonly",
                "HTMLTextAreaElement": "readonly",
                "HTMLTimeElement": "readonly",
                "HTMLTitleElement": "readonly",
                "HTMLTrackElement": "readonly",
                "HTMLUListElement": "readonly",
                "HTMLUnknownElement": "readonly",
                "HTMLVideoElement": "readonly",
                "IDBCursor": "readonly",
                "IDBCursorWithValue": "readonly",
                "IDBDatabase": "readonly",
                "IDBFactory": "readonly",
                "IDBIndex": "readonly",
                "IDBKeyRange": "readonly",
                "IDBObjectStore": "readonly",
                "IDBOpenDBRequest": "readonly",
                "IDBRequest": "readonly",
                "IDBTransaction": "readonly",
                "IDBVersionChangeEvent": "readonly",
                "IdleDeadline": "readonly",
                "IIRFilterNode": "readonly",
                "Image": "readonly",
                "ImageBitmap": "readonly",
                "ImageBitmapRenderingContext": "readonly",
                "ImageCapture": "readonly",
                "ImageData": "readonly",
                "indexedDB": "readonly",
                "innerHeight": "readonly",
                "innerWidth": "readonly",
                "InputEvent": "readonly",
                "IntersectionObserver": "readonly",
                "IntersectionObserverEntry": "readonly",
                "isSecureContext": "readonly",
                "KeyboardEvent": "readonly",
                "KeyframeEffect": "readonly",
                "KeyframeEffectReadOnly": "readonly",
                "length": "readonly",
                "localStorage": "readonly",
                "location": "writable",
                "Location": "readonly",
                "locationbar": "readonly",
                "matchMedia": "readonly",
                "MediaDeviceInfo": "readonly",
                "MediaDevices": "readonly",
                "MediaElementAudioSourceNode": "readonly",
                "MediaEncryptedEvent": "readonly",
                "MediaError": "readonly",
                "MediaKeyMessageEvent": "readonly",
                "MediaKeySession": "readonly",
                "MediaKeyStatusMap": "readonly",
                "MediaKeySystemAccess": "readonly",
                "MediaList": "readonly",
                "MediaMetadata": "readonly",
                "MediaQueryList": "readonly",
                "MediaQueryListEvent": "readonly",
                "MediaRecorder": "readonly",
                "MediaSettingsRange": "readonly",
                "MediaSource": "readonly",
                "MediaStream": "readonly",
                "MediaStreamAudioDestinationNode": "readonly",
                "MediaStreamAudioSourceNode": "readonly",
                "MediaStreamConstraints": "readonly",
                "MediaStreamEvent": "readonly",
                "MediaStreamTrack": "readonly",
                "MediaStreamTrackEvent": "readonly",
                "menubar": "readonly",
                "MIDIAccess": "readonly",
                "MIDIConnectionEvent": "readonly",
                "MIDIInput": "readonly",
                "MIDIInputMap": "readonly",
                "MIDIMessageEvent": "readonly",
                "MIDIOutput": "readonly",
                "MIDIOutputMap": "readonly",
                "MIDIPort": "readonly",
                "MimeType": "readonly",
                "MimeTypeArray": "readonly",
                "MouseEvent": "readonly",
                "moveBy": "readonly",
                "moveTo": "readonly",
                "MutationEvent": "readonly",
                "MutationObserver": "readonly",
                "MutationRecord": "readonly",
                "name": "readonly",
                "NamedNodeMap": "readonly",
                "NavigationPreloadManager": "readonly",
                "navigator": "readonly",
                "Navigator": "readonly",
                "NavigatorUAData": "readonly",
                "NetworkInformation": "readonly",
                "Node": "readonly",
                "NodeFilter": "readonly",
                "NodeIterator": "readonly",
                "NodeList": "readonly",
                "Notification": "readonly",
                "OfflineAudioCompletionEvent": "readonly",
                "OfflineAudioContext": "readonly",
                "offscreenBuffering": "readonly",
                "OffscreenCanvas": "writable",
                "OffscreenCanvasRenderingContext2D": "readonly",
                "onabort": "writable",
                "onafterprint": "writable",
                "onanimationend": "writable",
                "onanimationiteration": "writable",
                "onanimationstart": "writable",
                "onappinstalled": "writable",
                "onauxclick": "writable",
                "onbeforeinstallprompt": "writable",
                "onbeforeprint": "writable",
                "onbeforeunload": "writable",
                "onblur": "writable",
                "oncancel": "writable",
                "oncanplay": "writable",
                "oncanplaythrough": "writable",
                "onchange": "writable",
                "onclick": "writable",
                "onclose": "writable",
                "oncontextmenu": "writable",
                "oncuechange": "writable",
                "ondblclick": "writable",
                "ondevicemotion": "writable",
                "ondeviceorientation": "writable",
                "ondeviceorientationabsolute": "writable",
                "ondrag": "writable",
                "ondragend": "writable",
                "ondragenter": "writable",
                "ondragleave": "writable",
                "ondragover": "writable",
                "ondragstart": "writable",
                "ondrop": "writable",
                "ondurationchange": "writable",
                "onemptied": "writable",
                "onended": "writable",
                "onerror": "writable",
                "onfocus": "writable",
                "ongotpointercapture": "writable",
                "onhashchange": "writable",
                "oninput": "writable",
                "oninvalid": "writable",
                "onkeydown": "writable",
                "onkeypress": "writable",
                "onkeyup": "writable",
                "onlanguagechange": "writable",
                "onload": "writable",
                "onloadeddata": "writable",
                "onloadedmetadata": "writable",
                "onloadstart": "writable",
                "onlostpointercapture": "writable",
                "onmessage": "writable",
                "onmessageerror": "writable",
                "onmousedown": "writable",
                "onmouseenter": "writable",
                "onmouseleave": "writable",
                "onmousemove": "writable",
                "onmouseout": "writable",
                "onmouseover": "writable",
                "onmouseup": "writable",
                "onmousewheel": "writable",
                "onoffline": "writable",
                "ononline": "writable",
                "onpagehide": "writable",
                "onpageshow": "writable",
                "onpause": "writable",
                "onplay": "writable",
                "onplaying": "writable",
                "onpointercancel": "writable",
                "onpointerdown": "writable",
                "onpointerenter": "writable",
                "onpointerleave": "writable",
                "onpointermove": "writable",
                "onpointerout": "writable",
                "onpointerover": "writable",
                "onpointerup": "writable",
                "onpopstate": "writable",
                "onprogress": "writable",
                "onratechange": "writable",
                "onrejectionhandled": "writable",
                "onreset": "writable",
                "onresize": "writable",
                "onscroll": "writable",
                "onsearch": "writable",
                "onseeked": "writable",
                "onseeking": "writable",
                "onselect": "writable",
                "onstalled": "writable",
                "onstorage": "writable",
                "onsubmit": "writable",
                "onsuspend": "writable",
                "ontimeupdate": "writable",
                "ontoggle": "writable",
                "ontransitionend": "writable",
                "onunhandledrejection": "writable",
                "onunload": "writable",
                "onvolumechange": "writable",
                "onwaiting": "writable",
                "onwheel": "writable",
                "open": "readonly",
                "openDatabase": "readonly",
                "opener": "readonly",
                "Option": "readonly",
                "origin": "readonly",
                "OscillatorNode": "readonly",
                "outerHeight": "readonly",
                "outerWidth": "readonly",
                "OverconstrainedError": "readonly",
                "PageTransitionEvent": "readonly",
                "pageXOffset": "readonly",
                "pageYOffset": "readonly",
                "PannerNode": "readonly",
                "parent": "readonly",
                "Path2D": "readonly",
                "PaymentAddress": "readonly",
                "PaymentRequest": "readonly",
                "PaymentRequestUpdateEvent": "readonly",
                "PaymentResponse": "readonly",
                "Performance": "readonly",
                "PerformanceLongTaskTiming": "readonly",
                "PerformanceNavigation": "readonly",
                "PerformanceNavigationTiming": "readonly",
                "PerformancePaintTiming": "readonly",
                "PerformanceTiming": "readonly",
                "PeriodicWave": "readonly",
                "Permissions": "readonly",
                "PermissionStatus": "readonly",
                "personalbar": "readonly",
                "PhotoCapabilities": "readonly",
                "Plugin": "readonly",
                "PluginArray": "readonly",
                "PointerEvent": "readonly",
                "PopStateEvent": "readonly",
                "postMessage": "readonly",
                "Presentation": "readonly",
                "PresentationAvailability": "readonly",
                "PresentationConnection": "readonly",
                "PresentationConnectionAvailableEvent": "readonly",
                "PresentationConnectionCloseEvent": "readonly",
                "PresentationConnectionList": "readonly",
                "PresentationReceiver": "readonly",
                "PresentationRequest": "readonly",
                "print": "readonly",
                "ProcessingInstruction": "readonly",
                "ProgressEvent": "readonly",
                "PromiseRejectionEvent": "readonly",
                "prompt": "readonly",
                "PushManager": "readonly",
                "PushSubscription": "readonly",
                "PushSubscriptionOptions": "readonly",
                "RadioNodeList": "readonly",
                "Range": "readonly",
                "registerProcessor": "readonly",
                "RemotePlayback": "readonly",
                "removeEventListener": "readonly",
                "reportError": "readonly",
                "requestAnimationFrame": "readonly",
                "requestIdleCallback": "readonly",
                "resizeBy": "readonly",
                "ResizeObserver": "readonly",
                "ResizeObserverEntry": "readonly",
                "resizeTo": "readonly",
                "RTCCertificate": "readonly",
                "RTCDataChannel": "readonly",
                "RTCDataChannelEvent": "readonly",
                "RTCDtlsTransport": "readonly",
                "RTCIceCandidate": "readonly",
                "RTCIceGatherer": "readonly",
                "RTCIceTransport": "readonly",
                "RTCPeerConnection": "readonly",
                "RTCPeerConnectionIceEvent": "readonly",
                "RTCRtpContributingSource": "readonly",
                "RTCRtpReceiver": "readonly",
                "RTCRtpSender": "readonly",
                "RTCSctpTransport": "readonly",
                "RTCSessionDescription": "readonly",
                "RTCStatsReport": "readonly",
                "RTCTrackEvent": "readonly",
                "screen": "readonly",
                "Screen": "readonly",
                "screenLeft": "readonly",
                "ScreenOrientation": "readonly",
                "screenTop": "readonly",
                "screenX": "readonly",
                "screenY": "readonly",
                "ScriptProcessorNode": "readonly",
                "scroll": "readonly",
                "scrollbars": "readonly",
                "scrollBy": "readonly",
                "scrollTo": "readonly",
                "scrollX": "readonly",
                "scrollY": "readonly",
                "SecurityPolicyViolationEvent": "readonly",
                "Selection": "readonly",
                "self": "readonly",
                "ServiceWorker": "readonly",
                "ServiceWorkerContainer": "readonly",
                "ServiceWorkerRegistration": "readonly",
                "sessionStorage": "readonly",
                "ShadowRoot": "readonly",
                "SharedWorker": "readonly",
                "SourceBuffer": "readonly",
                "SourceBufferList": "readonly",
                "speechSynthesis": "readonly",
                "SpeechSynthesisEvent": "readonly",
                "SpeechSynthesisUtterance": "readonly",
                "StaticRange": "readonly",
                "status": "readonly",
                "statusbar": "readonly",
                "StereoPannerNode": "readonly",
                "stop": "readonly",
                "Storage": "readonly",
                "StorageEvent": "readonly",
                "StorageManager": "readonly",
                "styleMedia": "readonly",
                "StyleSheet": "readonly",
                "StyleSheetList": "readonly",
                "SubmitEvent": "readonly",
                "SVGAElement": "readonly",
                "SVGAngle": "readonly",
                "SVGAnimatedAngle": "readonly",
                "SVGAnimatedBoolean": "readonly",
                "SVGAnimatedEnumeration": "readonly",
                "SVGAnimatedInteger": "readonly",
                "SVGAnimatedLength": "readonly",
                "SVGAnimatedLengthList": "readonly",
                "SVGAnimatedNumber": "readonly",
                "SVGAnimatedNumberList": "readonly",
                "SVGAnimatedPreserveAspectRatio": "readonly",
                "SVGAnimatedRect": "readonly",
                "SVGAnimatedString": "readonly",
                "SVGAnimatedTransformList": "readonly",
                "SVGAnimateElement": "readonly",
                "SVGAnimateMotionElement": "readonly",
                "SVGAnimateTransformElement": "readonly",
                "SVGAnimationElement": "readonly",
                "SVGCircleElement": "readonly",
                "SVGClipPathElement": "readonly",
                "SVGComponentTransferFunctionElement": "readonly",
                "SVGDefsElement": "readonly",
                "SVGDescElement": "readonly",
                "SVGDiscardElement": "readonly",
                "SVGElement": "readonly",
                "SVGEllipseElement": "readonly",
                "SVGFEBlendElement": "readonly",
                "SVGFEColorMatrixElement": "readonly",
                "SVGFEComponentTransferElement": "readonly",
                "SVGFECompositeElement": "readonly",
                "SVGFEConvolveMatrixElement": "readonly",
                "SVGFEDiffuseLightingElement": "readonly",
                "SVGFEDisplacementMapElement": "readonly",
                "SVGFEDistantLightElement": "readonly",
                "SVGFEDropShadowElement": "readonly",
                "SVGFEFloodElement": "readonly",
                "SVGFEFuncAElement": "readonly",
                "SVGFEFuncBElement": "readonly",
                "SVGFEFuncGElement": "readonly",
                "SVGFEFuncRElement": "readonly",
                "SVGFEGaussianBlurElement": "readonly",
                "SVGFEImageElement": "readonly",
                "SVGFEMergeElement": "readonly",
                "SVGFEMergeNodeElement": "readonly",
                "SVGFEMorphologyElement": "readonly",
                "SVGFEOffsetElement": "readonly",
                "SVGFEPointLightElement": "readonly",
                "SVGFESpecularLightingElement": "readonly",
                "SVGFESpotLightElement": "readonly",
                "SVGFETileElement": "readonly",
                "SVGFETurbulenceElement": "readonly",
                "SVGFilterElement": "readonly",
                "SVGForeignObjectElement": "readonly",
                "SVGGElement": "readonly",
                "SVGGeometryElement": "readonly",
                "SVGGradientElement": "readonly",
                "SVGGraphicsElement": "readonly",
                "SVGImageElement": "readonly",
                "SVGLength": "readonly",
                "SVGLengthList": "readonly",
                "SVGLinearGradientElement": "readonly",
                "SVGLineElement": "readonly",
                "SVGMarkerElement": "readonly",
                "SVGMaskElement": "readonly",
                "SVGMatrix": "readonly",
                "SVGMetadataElement": "readonly",
                "SVGMPathElement": "readonly",
                "SVGNumber": "readonly",
                "SVGNumberList": "readonly",
                "SVGPathElement": "readonly",
                "SVGPatternElement": "readonly",
                "SVGPoint": "readonly",
                "SVGPointList": "readonly",
                "SVGPolygonElement": "readonly",
                "SVGPolylineElement": "readonly",
                "SVGPreserveAspectRatio": "readonly",
                "SVGRadialGradientElement": "readonly",
                "SVGRect": "readonly",
                "SVGRectElement": "readonly",
                "SVGScriptElement": "readonly",
                "SVGSetElement": "readonly",
                "SVGStopElement": "readonly",
                "SVGStringList": "readonly",
                "SVGStyleElement": "readonly",
                "SVGSVGElement": "readonly",
                "SVGSwitchElement": "readonly",
                "SVGSymbolElement": "readonly",
                "SVGTextContentElement": "readonly",
                "SVGTextElement": "readonly",
                "SVGTextPathElement": "readonly",
                "SVGTextPositioningElement": "readonly",
                "SVGTitleElement": "readonly",
                "SVGTransform": "readonly",
                "SVGTransformList": "readonly",
                "SVGTSpanElement": "readonly",
                "SVGUnitTypes": "readonly",
                "SVGUseElement": "readonly",
                "SVGViewElement": "readonly",
                "TaskAttributionTiming": "readonly",
                "Text": "readonly",
                "TextEvent": "readonly",
                "TextMetrics": "readonly",
                "TextTrack": "readonly",
                "TextTrackCue": "readonly",
                "TextTrackCueList": "readonly",
                "TextTrackList": "readonly",
                "TimeRanges": "readonly",
                "ToggleEvent": "readonly",
                "toolbar": "readonly",
                "top": "readonly",
                "Touch": "readonly",
                "TouchEvent": "readonly",
                "TouchList": "readonly",
                "TrackEvent": "readonly",
                "TransitionEvent": "readonly",
                "TreeWalker": "readonly",
                "UIEvent": "readonly",
                "ValidityState": "readonly",
                "visualViewport": "readonly",
                "VisualViewport": "readonly",
                "VTTCue": "readonly",
                "WaveShaperNode": "readonly",
                "WebGL2RenderingContext": "readonly",
                "WebGLActiveInfo": "readonly",
                "WebGLBuffer": "readonly",
                "WebGLContextEvent": "readonly",
                "WebGLFramebuffer": "readonly",
                "WebGLProgram": "readonly",
                "WebGLQuery": "readonly",
                "WebGLRenderbuffer": "readonly",
                "WebGLRenderingContext": "readonly",
                "WebGLSampler": "readonly",
                "WebGLShader": "readonly",
                "WebGLShaderPrecisionFormat": "readonly",
                "WebGLSync": "readonly",
                "WebGLTexture": "readonly",
                "WebGLTransformFeedback": "readonly",
                "WebGLUniformLocation": "readonly",
                "WebGLVertexArrayObject": "readonly",
                "WebSocket": "readonly",
                "WheelEvent": "readonly",
                "window": "readonly",
                "Window": "readonly",
                "Worker": "readonly",
                "XMLDocument": "readonly",
                "XMLHttpRequest": "readonly",
                "XMLHttpRequestEventTarget": "readonly",
                "XMLHttpRequestUpload": "readonly",
                "XMLSerializer": "readonly",
                "XPathEvaluator": "readonly",
                "XPathExpression": "readonly",
                "XPathResult": "readonly",
                "XRAnchor": "readonly",
                "XRBoundedReferenceSpace": "readonly",
                "XRCPUDepthInformation": "readonly",
                "XRDepthInformation": "readonly",
                "XRFrame": "readonly",
                "XRInputSource": "readonly",
                "XRInputSourceArray": "readonly",
                "XRInputSourceEvent": "readonly",
                "XRInputSourcesChangeEvent": "readonly",
                "XRPose": "readonly",
                "XRReferenceSpace": "readonly",
                "XRReferenceSpaceEvent": "readonly",
                "XRRenderState": "readonly",
                "XRRigidTransform": "readonly",
                "XRSession": "readonly",
                "XRSessionEvent": "readonly",
                "XRSpace": "readonly",
                "XRSystem": "readonly",
                "XRView": "readonly",
                "XRViewerPose": "readonly",
                "XRViewport": "readonly",
                "XRWebGLBinding": "readonly",
                "XRWebGLDepthInformation": "readonly",
                "XRWebGLLayer": "readonly",
                "XSLTProcessor": "readonly",
                "NodeJS": "writable",
                "__APP_VERSION__": "writable",
                "__APP_LICENSE__": "writable"
              },
              "ignorePatterns": [
                "dist",
                "node_modules",
                "dist_electron",
                "dist-electron",
                "release",
                "index.html",
                "tools/**/*.js",
                "uno.config.ts",
                "vite.config.ts",
                "*.d.ts"
              ],
              "rules": {
                "constructor-super": "error",
                "for-direction": "error",
                "getter-return": "error",
                "no-async-promise-executor": "error",
                "no-case-declarations": "error",
                "no-class-assign": "error",
                "no-compare-neg-zero": "error",
                "no-cond-assign": "error",
                "no-const-assign": "error",
                "no-constant-binary-expression": "error",
                "no-constant-condition": "error",
                "no-control-regex": "error",
                "no-debugger": "error",
                "no-delete-var": "error",
                "no-dupe-class-members": "error",
                "no-dupe-else-if": "error",
                "no-dupe-keys": "error",
                "no-duplicate-case": "error",
                "no-empty": "error",
                "no-empty-character-class": "error",
                "no-empty-pattern": "error",
                "no-empty-static-block": "error",
                "no-ex-assign": "error",
                "no-extra-boolean-cast": "error",
                "no-fallthrough": "error",
                "no-func-assign": "error",
                "no-global-assign": "error",
                "no-import-assign": "error",
                "no-invalid-regexp": "error",
                "no-irregular-whitespace": "error",
                "no-loss-of-precision": "error",
                "no-misleading-character-class": "error",
                "no-new-native-nonconstructor": "error",
                "no-nonoctal-decimal-escape": "error",
                "no-obj-calls": "error",
                "no-prototype-builtins": "error",
                "no-redeclare": "error",
                "no-regex-spaces": "error",
                "no-self-assign": "error",
                "no-setter-return": "error",
                "no-shadow-restricted-names": "error",
                "no-sparse-arrays": "error",
                "no-this-before-super": "error",
                "no-undef": "error",
                "no-unexpected-multiline": "error",
                "no-unreachable": "error",
                "no-unsafe-finally": "error",
                "no-unsafe-negation": "error",
                "no-unsafe-optional-chaining": "error",
                "no-unused-labels": "error",
                "no-unused-private-class-members": "error",
                "no-unused-vars": "error",
                "no-useless-backreference": "error",
                "no-useless-catch": "error",
                "no-useless-escape": "error",
                "no-with": "error",
                "require-yield": "error",
                "use-isnan": "error",
                "valid-typeof": "error",
                "no-array-constructor": "error",
                "no-unused-expressions": "error",
                "vue/no-arrow-functions-in-watch": "error",
                "vue/no-deprecated-data-object-declaration": "error",
                "vue/no-deprecated-delete-set": "error",
                "vue/no-deprecated-destroyed-lifecycle": "error",
                "vue/no-deprecated-events-api": "error",
                "vue/no-deprecated-model-definition": "error",
                "vue/no-deprecated-vue-config-keycodes": "error",
                "vue/no-export-in-script-setup": "error",
                "vue/no-lifecycle-after-await": "error",
                "vue/prefer-import-from-vue": "error",
                "vue/return-in-computed-property": "error",
                "vue/valid-define-emits": "error",
                "vue/valid-define-props": "error",
                "vue/no-multiple-slot-args": "warn",
                "vue/no-required-prop-with-default": "warn",
                "unocss/order": "warn",
                "unocss/order-attributify": "warn",
                "typescript/await-thenable": "error",
                "typescript/ban-ts-comment": "error",
                "typescript/no-array-delete": "error",
                "typescript/no-base-to-string": "error",
                "typescript/no-duplicate-enum-values": "error",
                "typescript/no-duplicate-type-constituents": "error",
                "typescript/no-empty-object-type": "error",
                "typescript/no-explicit-any": "error",
                "typescript/no-extra-non-null-assertion": "error",
                "typescript/no-floating-promises": "error",
                "typescript/no-for-in-array": "error",
                "typescript/no-implied-eval": "error",
                "typescript/no-misused-new": "error",
                "typescript/no-misused-promises": "error",
                "typescript/no-namespace": "error",
                "typescript/no-non-null-asserted-optional-chain": "error",
                "typescript/no-redundant-type-constituents": "error",
                "typescript/no-require-imports": "error",
                "typescript/no-this-alias": "error",
                "typescript/no-unnecessary-type-assertion": "error",
                "typescript/no-unnecessary-type-constraint": "error",
                "typescript/no-unsafe-argument": "error",
                "typescript/no-unsafe-assignment": "error",
                "typescript/no-unsafe-call": "error",
                "typescript/no-unsafe-declaration-merging": "error",
                "typescript/no-unsafe-enum-comparison": "error",
                "typescript/no-unsafe-function-type": "error",
                "typescript/no-unsafe-member-access": "error",
                "typescript/no-unsafe-return": "error",
                "typescript/no-unsafe-unary-minus": "error",
                "typescript/no-wrapper-object-types": "error",
                "typescript/only-throw-error": "error",
                "typescript/prefer-as-const": "error",
                "typescript/prefer-namespace-keyword": "error",
                "typescript/prefer-promise-reject-errors": "error",
                "typescript/require-await": "error",
                "typescript/restrict-plus-operands": "error",
                "typescript/restrict-template-expressions": "error",
                "typescript/triple-slash-reference": "error",
                "typescript/unbound-method": "error"
              },
              "overrides": [
                {
                  "files": [
                    "**/*.ts",
                    "**/*.tsx",
                    "**/*.mts",
                    "**/*.cts"
                  ],
                  "rules": {
                    "constructor-super": "off",
                    "getter-return": "off",
                    "no-class-assign": "off",
                    "no-const-assign": "off",
                    "no-dupe-class-members": "off",
                    "no-dupe-keys": "off",
                    "no-func-assign": "off",
                    "no-import-assign": "off",
                    "no-new-native-nonconstructor": "off",
                    "no-obj-calls": "off",
                    "no-redeclare": "off",
                    "no-setter-return": "off",
                    "no-this-before-super": "off",
                    "no-undef": "off",
                    "no-unreachable": "off",
                    "no-unsafe-negation": "off",
                    "no-var": "error",
                    "no-with": "off",
                    "prefer-const": "error",
                    "prefer-rest-params": "error",
                    "prefer-spread": "error"
                  }
                }
              ]
            },
            staged: {
              "*.?(js|ts|ts|vue)": [
                "vp fmt",
                "vp lint"
              ]
            },
            fmt: {
              tabWidth: 2,
              arrowParens: "always",
              singleAttributePerLine: true,
              bracketSameLine: false,
              trailingComma: "all",
              quoteProps: "consistent",
              importOrderTypeScriptVersion: "4.4.0",
              importOrder: [
                "^(electron/(.*)$)|^(electron$)",
                "^(vue/(.*)$)|^(vue$)",
                "<THIRD_PARTY_MODULES>",
                "",
                "^~/(.*)$",
                "^[./]",
              ],
              printWidth: 80,
              sortPackageJson: {},
              ignorePatterns: [".github", ".vscode", "i18n", "*.yaml", "*.md", "*.json"],
            },
            host: url.hostname,
            port: +url.port,
            hrm: true,
          }
        })()
      : { hmr: true },
    clearScreen: false,
  } satisfies UserConfig;
});
