<template>
  <div id="help" ref="help" v-on:scroll="scrollHandle">
    <ol>
      <li>
        Configure WeakAuras Companion, you will need at least to set your Wold
        Of Warcraft folder and Account
      </li>
      <li>
        Fetch updates, this is done automatically once every hour
        <ol>
          <li>Companion make a list of your auras with a link to wago</li>
          <li>Companion send the list to Wago API and compare versions</li>
          <li>Wago send updated import strings</li>
          <li>
            Companion create a new "WeakAurasCompanion" addon automatically,
            this is where new import strings are saved
          </li>
        </ol>
      </li>

      <li>
        Update your auras in-game by clicking the update button
        <img :src="require(`@/assets/wagoupdate_logo.png`)" /> in WeakAuras
        Options<br />
        <img :src="require(`@/assets/ingame.png`)" class="imgex" /><br /><br />
        <div class="container">
          <div class="wowbox">
            <span class="top">World of Warcraft<br />Addons</span><br /><br />
            <div class="box mid" ref="weakaurasAddon">
              <span class="center">WeakAuras</span>
            </div>
            <img
              :src="require(`@/assets/wagoupdate_logo.png`)"
              class="updateButton"
            />
            <div class="box mid" ref="weakaurasCompanionAddon">
              <span class="center">WeakAuras Companion</span>
            </div>
            <div class="postscriptum">generated by app</div>
            <br />
          </div>
          <div class="dummybox">
            <div class="box center" ref="weakaurasCompanion">
              <img :src="require(`@/assets/wa_logo.png`)" class="logo" />
              <span class="top">companion</span>
            </div>
          </div>
          <div class="dummybox">
            <div class="box center" ref="wago">
              <img :src="require(`@/assets/wago_plain.png`)" class="logo" />
              <span class="top">wago</span>
            </div>
          </div>
        </div>
        <div class="legends">
          <div class="legend1" ref="legend1"></div>
          <div class="legend2" ref="legend2"></div>
        </div>
        <br /><br /><br />
      </li>
      <li>
        You can skip a version or ignore completely updates for each auras<br />
        <img :src="require(`@/assets/ingame2.png`)" class="imgex" />
      </li>
    </ol>
    <br /><br />
  </div>
</template>

<script>
const LeaderLine = require("leader-line");

export default {
  data() {
    return {
      lines: []
    };
  },
  mounted() {
    // eslint-disable-next-line no-new
    this.lines.push(
      new LeaderLine(
        this.$refs.weakaurasAddon,
        LeaderLine.pointAnchor(this.$refs.weakaurasCompanion, {
          x: 0,
          y: 40
        }),
        {
          endLabel: LeaderLine.captionLabel({
            text: "2.1",
            color: "white",
            outlineColor: "none",
            offset: [-40, -80]
          }),
          path: "straight",
          dash: { len: 4, gap: 8 }
        }
      )
    );
    this.lines.push(
      new LeaderLine(
        LeaderLine.pointAnchor(this.$refs.weakaurasCompanion, {
          x: 128,
          y: 40
        }),
        LeaderLine.pointAnchor(this.$refs.wago, {
          x: 0,
          y: 40
        }),
        {
          endLabel: LeaderLine.captionLabel({
            text: "2.2",
            color: "white",
            outlineColor: "none",
            offset: [-50, -40]
          }),
          path: "straight",
          dash: { len: 4, gap: 8 }
        }
      )
    );
    this.lines.push(
      new LeaderLine(
        LeaderLine.pointAnchor(this.$refs.wago, {
          x: 0,
          y: 90
        }),
        LeaderLine.pointAnchor(this.$refs.weakaurasCompanion, {
          x: 128,
          y: 90
        }),
        {
          endLabel: LeaderLine.captionLabel({
            text: "2.3",
            color: "white",
            outlineColor: "none",
            offset: [22, 5]
          }),
          path: "straight",
          dash: { animation: true }
        }
      )
    );
    this.lines.push(
      new LeaderLine(
        LeaderLine.pointAnchor(this.$refs.weakaurasCompanion, {
          x: 0,
          y: 90
        }),
        this.$refs.weakaurasCompanionAddon,
        {
          endLabel: LeaderLine.captionLabel({
            text: "2.4",
            color: "white",
            outlineColor: "none",
            offset: [42, -15]
          }),
          path: "straight",
          dash: { animation: true }
        }
      )
    );
    this.lines.push(
      new LeaderLine(
        this.$refs.weakaurasCompanionAddon,
        this.$refs.weakaurasAddon,
        {
          endLabel: LeaderLine.captionLabel({
            text: "3",
            color: "white",
            outlineColor: "none",
            offset: [-20, 15]
          }),
          path: "straight",
          dash: { animation: true }
        }
      )
    );
    this.lines.push(
      new LeaderLine(
        LeaderLine.pointAnchor(this.$refs.legend1, { x: 0, y: 20 }),
        LeaderLine.pointAnchor(this.$refs.legend2, { x: 0, y: 20 }),
        {
          path: "straight",
          dash: { len: 4, gap: 8 },
          middleLabel: LeaderLine.pathLabel({
            text: "auras list",
            color: "white",
            outlineColor: "none"
          })
        }
      )
    );
    this.lines.push(
      new LeaderLine(
        LeaderLine.pointAnchor(this.$refs.legend1, { x: 0, y: 60 }),
        LeaderLine.pointAnchor(this.$refs.legend2, { x: 0, y: 60 }),
        {
          path: "straight",
          dash: { animation: true },
          middleLabel: LeaderLine.pathLabel({
            text: "import string",
            color: "white",
            outlineColor: "none"
          })
        }
      )
    );
  },
  beforeDestroy() {
    this.lines.forEach(line => line.remove());
    this.lines = [];
  },
  methods: {
    scrollHandle() {
      this.lines.forEach(line => line.position());
    }
  }
};
</script>

<style scoped>
#help {
  padding: 10px 50px;
  text-align: left;
  height: 100%;
  position: relative;
  overflow: auto;
}
.container {
  display: flex;
  justify-content: center;
}
.box {
  width: 128px;
  height: 128px;
  background-color: #333;
  border-radius: 17px;
  position: relative;
  margin: 10px;
}
.wowbox,
.dummybox {
  position: relative;
  width: 200px;
}
.wowbox {
  background-color: #222;
  border-radius: 17px;
}
.logo {
  width: 128px;
  height: 128px;
}
.top {
  position: absolute;
  top: 5px;
  width: 100%;
  left: 50%;
  margin-left: -50%;
  text-align: center;
}
.center {
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
  text-align: center;
}
.mid {
  left: 50%;
  margin-left: -64px;
}
.legends {
  margin: 0 60% 0 40%;
  width: 60%;
}
.postscriptum {
  width: 200px;
  font-size: x-small;
  text-align: center;
  transform: translate(0, -8px);
  color: #bbb;
}
.legend1,
.legend2 {
  width: 0px;
  height: 40px;
  margin: 0 130px 0 0;
}
.legend1 {
  display: inline-block;
}
.legend2 {
  display: inline-block;
}
.updateButton {
  margin-left: 60%;
}
ol {
  counter-reset: item;
  padding-left: 10px;
  font-size: small;
  margin-left: 20px;
}
li {
  display: block;
  margin-top: 7px;
}
li:before {
  content: counters(item, ".") ". ";
  counter-increment: item;
}
li > img {
  transform: translate(0, 8px);
}
.imgex {
  position: relative;
  left: 50%;
  transform: translate(-50%, 0);
  margin: 10px 0;
}
</style>
