name: Linux Build
on:
  push:
    branches:
      - "*"
    tags:
      - "*"
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: ["24"]

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false
      - uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v6
        with:
          node-version: ${{ matrix.node }}
          package-manager-cache: false

      - name: Install Dependencies
        run: pnpm install

      - name: Lint
        run: pnpm run lint

      - name: Build
        if: github.ref == 'refs/heads/main'
        run: pnpm run build
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Build
        if: github.ref != 'refs/heads/main'
        run: pnpm run build --publish=never
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        name: Upload AppImage
        with:
          name: WeakAuras-Companion-CI-AppImage
          path: release/**/*.AppImage

      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        name: Upload Snap
        with:
          name: WeakAuras-Companion-CI-Snap
          path: release/**/*.snap

      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        name: Upload deb
        with:
          name: WeakAuras-Companion-CI-deb
          path: release/**/*.deb

      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        name: Upload rpm
        with:
          name: WeakAuras-Companion-CI-rpm
          path: release/**/*.rpm
