name: macOS Build
on: pull_request

jobs:
  build:
    runs-on: macos-12

    strategy:
      matrix:
        node: ["16"]

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - name: Install Dependencies
        run: pnpm install

      - run: pnpm i -D dmg-license

      - name: Lint
        run: pnpm run lint

      - name: Rebuild
        run: npm rebuild node-sass

      - name: Build
        run: pnpm run build --publish=never
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - uses: actions/upload-artifact@v3
        name: Upload DMG
        with:
          name: WeakAuras-Companion-PRCI-dmg
          path: dist_electron/*-mac-universal.dmg

      - uses: actions/upload-artifact@v3
        name: Upload ZIP
        with:
          name: WeakAuras-Companion-PRCI-zip
          path: dist_electron/*-mac-universal.zip
