name: macOS Build
on: pull_request

jobs:
  build:
    runs-on: macOS-latest

    strategy:
      matrix:
        node: ["10", "12"]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Install
        run: yarn
        env:
          CI: true

      - name: Lint
        run: yarn lint

      - name: Build
        run: yarn dist:pr
        env:
          CI: true

      - name: Package Artifacts
        run: |
          mkdir artifact-pkg
          mv dist_electron/*.pkg artifact-pkg/
          mkdir artifact-zip
          mv dist_electron/*.zip artifact-zip/

      - uses: actions/upload-artifact@master
        name: Upload PKG
        with:
          name: macOS .pkg
          path: artifact-pkg

      - uses: actions/upload-artifact@master
        name: Upload ZIP
        with:
          name: macOS .zip
          path: artifact-zip
