name: macOS Build
on:
  push:
    branches:
      - "*"
    tags:
      - "*"
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: macos-14

    strategy:
      matrix:
        node: ["24"]

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false
      - uses: pnpm/action-setup@0e279bb959325dab635dd2c09392533439d90093 # v6

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: ${{ matrix.node }}
          package-manager-cache: false

      - name: Install Dependencies
        run: pnpm install

      - name: Lint
        run: pnpm run lint

      - name: Sharp Multiarch Rebuild
        run: pnpm install --config.platform=darwin --config.arch=x64 sharp && pnpm --config.platform=darwin --config.arch=arm64 rebuild sharp

      - name: Build
        if: github.ref == 'refs/heads/main'
        run: pnpm run build
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Build
        if: github.ref != 'refs/heads/main'
        run: pnpm run build --publish=never
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        name: Upload DMG
        with:
          name: WeakAuras-Companion-CI-dmg
          path: release/**/*-mac-universal.dmg

      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        name: Upload ZIP
        with:
          name: WeakAuras-Companion-CI-zip
          path: release/**/*-mac-universal.zip
